# Generated by Django 2.2.5 on 2019-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191114_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
