# Generated by Django 2.2.5 on 2019-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191119_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
